### ISSUE TITLE
能否增添一个导出所有QQ群号的功能？

### ISSUE THREAD

**Issue by Forgo7ten** [cjh0613/python-pub#1]

**Comment by Forgo7ten** [comment]
就想保存一下qq好友和q群，最近tx封号有些严重，，，q群里的成员信息对我用处不算大，，，
害，不懂爬虫

**Comment by cjh0613** [comment]
理论可以。试试[我现在修改完成的代码](https://github.com/cjh0613/python-pub/blob/master/获取QQ群号列表.py)，应该可行，但还没有测试过。
