### ISSUE TITLE
[报告问题] 成品 超星链接已失效

### ISSUE THREAD

**Issue by Forgo7ten** [cjh0613/python-pub#3]
假期学了python爬虫，正在学selenium。发现chromedriver默认打开的是系统里安装的chrome，而不是我的绿化版chrome。我记得您的成品是附带了一个chrome来进行模拟操作，于是想下载下来学习学习

**Comment by cjh0613** [comment]
我发现超星云盘已经没有分享功能了。

**Comment by Forgo7ten** [comment]
> 我发现超星云盘已经没有分享功能了。

没关系，感谢。问题已经解决，我在谷歌上找到了答案
